name: Update Insider Trading Data

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Collect insider trading data
        run: |
          # Set up environment with GitHub-provided email
          sed -i 's/insidertrading-api@example.com/github-actions@github.com/g' InsiderTrading.py
          # Create data directory structure
          mkdir -p data/sec-edgar-filings
          # First run with no-download to just create initial database
          python InsiderTrading.py --no-download
          # Then fetch a limited amount of data to avoid timeouts
          python InsiderTrading.py --limit 5
      
      - name: Export data to JSON for API
        run: |
          python export_json.py
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Commit and push JSON files
        run: |
          git add data/json/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update insider trading JSON data [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}