name: Update Insider Trading Data

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8:00 UTC
  workflow_dispatch:  # Allow manual triggering

# Add global permissions for the workflow
permissions:
  contents: write  # This is important for pushing changes
  pages: write

jobs:
  update_data:
    runs-on: ubuntu-latest
    # Add job-specific permissions
    permissions:
      contents: write  # Required for git push
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Collect insider trading data
        run: |
          # Set up environment with a valid email (SEC requires a valid email)
          sed -i 's/insidertrading-api@example.com/action@github.com/g' InsiderTrading.py
          
          # Create data directory structure with some sample files
          mkdir -p data/sec-edgar-filings
          mkdir -p data/json
          
          # Create sample file to avoid errors in no-download mode
          mkdir -p data/sec-edgar-filings/AAPL/4/sample
          echo '<ownershipDocument></ownershipDocument>' > data/sec-edgar-filings/AAPL/4/sample/primary-document.xml
          
          # Initialize the database and check if it works
          echo "Running with --no-download flag to initialize database..."
          python InsiderTrading.py --no-download || echo "No-download mode completed with status $?"
          
          # Ensure the export_json.py runs correctly even with minimal data
          touch data/insider_trading.db
          python export_json.py || echo "JSON export completed with status $?"
          
          # Try to fetch a very small amount of data (just 1 company)
          echo "Attempting to download data for 1 company..."
          python InsiderTrading.py --limit 1 || echo "Download completed with status $?"
      
      - name: Export data to JSON for API
        run: |
          python export_json.py
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Commit and push JSON files
        run: |
          echo "Staging JSON files..."
          git add data/json/
          
          # Check if there are changes to commit
          if git diff --quiet --staged; then
            echo "No changes to commit, skipping push"
          else
            echo "Changes detected, committing..."
            git commit -m "Update insider trading JSON data [skip ci]"
            
            # Push using the token for authentication
            echo "Pushing changes to the repository..."
            git push "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git" HEAD:main
          fi